version: '3'

services:

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   hostname: certbot
  #   volumes:
  #     - ./data/ssl:/etc/letsencrypt
  #   ports:
  #     - 80:80
  #   command: certonly --non-interactive --keep-until-expiring --standalone --preferred-challenges http --agree-tos --email mail@example.com -d example.com

  openconnect:
    # depends_on:
    #   certbot:
    #     condition: service_completed_successfully
    image: openconnect:v1.3
    container_name: openconnect
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 200M
    cap_add:
      - NET_ADMIN
    hostname: openconnect
    environment:
      - TZ="Europe/Moscow"
      - SRV_CN=example.com
      - SRV_CA="Example CA"
    volumes:
      - ./data:/etc/ocserv
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 43443:443/tcp